// <auto-generated />
namespace mvcWithMosh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class included_IDENTITY_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(included_IDENTITY_));
        
        string IMigrationMetadata.Id
        {
            get { return "202202270730065_included_IDENTITY_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
